FROM r-base:4.2.0

# Install required Bioconductor packages
RUN R -e 'install.packages("BiocManager")'
RUN R -e 'BiocManager::install(version="3.15")'
#RUN R -e 'BiocManager::install("GenomicRanges")'
#RUN R -e 'BiocManager::install("Rsamtools")'
#RUN R -e 'BiocManager::install("SingleCellExperiment")'
#RUN R -e 'BiocManager::install("scran")'
#RUN R -e 'BiocManager::install("scater")'
#RUN R -e 'BiocManager::install("batchelor")'

RUN R -e 'install.packages("Seurat")'
RUN R -e 'install.packages("data.table")'
RUN R -e 'install.packages("ggplot2")'
RUN R -e 'install.packages("igraph")'
RUN R -e 'install.packages("dyplr")'
