#!bin/env bash

<<'//_SUMMARY_//'
Download Seurat image to create container for analysis
//_SUMMARY_//


<<'//_TASKS_//'
2023-04-08
Some time ago I created a image. Now I will add more functionalities to it and save it to an updated version
I run into issues, could not make the image work today. I will resume tomorrow
2023-04-09
Done - Uploaded to Bianca
//_TASKS_//
